In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [2]:
path = '/content/drive/MyDrive/Core Project/data.csv'

In [3]:
import pandas as pd
df = pd.read_csv(path)
print(df.head())

   Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales
1   49        No  Travel_Frequently        279  Research & Development
2   37       Yes      Travel_Rarely       1373  Research & Development
3   33        No  Travel_Frequently       1392  Research & Development
4   27        No      Travel_Rarely        591  Research & Development

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1
1                 8          1  Life Sciences              1               2
2                 2          2          Other              1               4
3                 3          4  Life Sciences              1               5
4                 2          1        Medical              1               7

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0
1  ...                         4            80                 1
2  ...                         2            80                 0
3  ...                         3            80                 0
4  ...                         4            80                 1

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6
1                 10                      3               3              10
2                  7                      3               3               0
3                  8                      3               3               8
4                  6                      3               3               2

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager
0                  4                        0                     5
1                  7                        1                     7
2                  0                        0                     0
3                  7                        3                     0
4                  2                        2                     2

[5 rows x 35 columns]

In [4]:
# Doing one hot encoding of categorical variables
df['BusinessTravel']=df['BusinessTravel'].replace(['Non-Travel','Travel_Rarely','Travel_Frequently'], [0,1,2])
# Departments
df['Department']=df['Department'].astype('category')
dummies=pd.get_dummies(df['Department'],prefix='Department')
df = pd.concat([df, dummies], axis=1)
del df['Department']
# Education Field
df['EducationField']=df['EducationField'].astype('category')
dummies=pd.get_dummies(df['EducationField'],prefix='EducationField')
df = pd.concat([df, dummies], axis=1)
del df['EducationField']
# Gender
df['Gender']=df['Gender'].astype('category')
dummies=pd.get_dummies(df['Gender'],prefix='Gender')
df = pd.concat([df, dummies], axis=1)
del df['Gender']
# JobRole
df['JobRole']=df['JobRole'].astype('category')
dummies=pd.get_dummies(df['JobRole'],prefix='JobRole')
df = pd.concat([df, dummies], axis=1)
del df['JobRole']
# MaritalStatus
df['MaritalStatus']=df['MaritalStatus'].astype('category')
dummies=pd.get_dummies(df['MaritalStatus'],prefix='MaritalStatus')
df = pd.concat([df, dummies], axis=1)
del df['MaritalStatus']
# Dropping over 18 as its giving no data
del df['Over18']
#Dropping standard hours as it makes no sense
del df['StandardHours']


df['OverTime']=df['OverTime'].replace(['No','Yes'], [0,1])

df.head()

,Age,Attrition,BusinessTravel,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single
0,41,Yes,1,1102,1,2,1,1,2,94,...,False,False,False,False,False,True,False,False,False,True
1,49,No,2,279,8,1,1,2,3,61,...,False,False,False,False,True,False,False,False,True,False
2,37,Yes,1,1373,2,2,1,4,4,92,...,True,False,False,False,False,False,False,False,False,True
3,33,No,2,1392,3,4,1,5,4,56,...,False,False,False,False,True,False,False,False,True,False
4,27,No,1,591,2,1,1,7,1,40,...,True,False,False,False,False,False,False,False,True,False

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn import metrics

In [6]:
x = df.drop('Attrition', axis=1)  # Features
y = df['Attrition']  # Target
x_train  , x_test , y_train, y_test = train_test_split (x ,y ,test_size = 0.2 , random_state = 0)

In [7]:
oversampler=SMOTE(random_state=0)
smote_train, smote_target = oversampler.fit_resample(x_train,y_train)

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 42)

rfc = RandomForestClassifier()
rfc = rfc.fit(smote_train , smote_target)
y_pred = rfc.predict(x_test)


accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')

Accuracy: 0.9693877551020408
Confusion Matrix:
[[253   2]
 [  7  32]]
Classification Report:
              precision    recall  f1-score   support

          No       0.97      0.99      0.98       255
         Yes       0.94      0.82      0.88        39

    accuracy                           0.97       294
   macro avg       0.96      0.91      0.93       294
weighted avg       0.97      0.97      0.97       294